import { Pricing } from './pricing';
export interface Product {
    id?:string,
    name?:string,
    displayName?:string,
    description?:string,
    tags?:string[],
    fssiLicenceNo?:string,
    veg?:boolean,
    pricing?:Pricing,
    subCategoryId?:string,
    linkToNutritionChart?:string,
    images?:string[],
    rating?:number,
    inStock?:boolean,
    location?:any,
    shelfLife?:string,
    howToUse?:string,
    ingredients?:string,
    fssiMark?:string,
    packagingInfo?:any,
    manufacturer?:any,
    contactTo?:string,
    contactToNo?:string,
    caution?:string,
    storageInfo?:string,
    active?:boolean,
    trend?:string,
    searchString?:string,
    tempImages?:string[],
    price?:number,
    offerprice?:number,

}
